### ISSUE TITLE
1.18.2 Forge Startup crash: Mixin apply failed

### ISSUE THREAD

**Issue by xFirefalconx** [bloxgate/TagFoods#3]
Modpack dev here. I added your mod (among ... >100 others) to my pack. Apparently, there's an issue, not yet sure whether it's caused by the mod itself or a compatibility issue. 

[latest.log](https://github.com/bloxgate/TagFoods/files/13533586/latest.log)

Let me know if you need further information. I'll debug it later once I figured whether there's another clown in the mods I picked. 

No crash log was produced but the latest.log shows the following:

```
pool-4-thread-1
Mixin apply failed tagfoods.mixins.json:MixinHolder -> net.minecraft.core.Holder$Reference: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Shadow field tags was not located in the target class net.minecraft.core.Holder$Reference. Using refmap tagfoods.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Shadow field tags was not located in the target class net.minecraft.core.Holder$Reference. Using refmap tagfoods.refmap.json
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachFields(MixinPreProcessorStandard.java:629)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:305)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:280)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1288)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:292)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:250)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.service.modlauncher.MixinTransformationHandler.processClass(MixinTransformationHandler.java:131)
	at MC-BOOTSTRAP/org.spongepowered.mixin/org.spongepowered.asm.launch.MixinLaunchPluginLegacy.processClass(MixinLaunchPluginLegacy.java:131)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:156)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.1.3/cpw.mods.modlauncher.TransformingClassLoader.maybeTransformClassBytes(TransformingClassLoader.java:50)at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.readerToClass(ModuleClassLoader.java:113)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.lambda$findClass$15(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadFromModule(ModuleClassLoader.java:229)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.findClass(ModuleClassLoader.java:219)
	at cpw.mods.securejarhandler@1.0.8/cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:135)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.core.Registry.<clinit>(Registry.java:167)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.Bootstrap.m_135870_(Bootstrap.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.client.main.Main.lambda$main$0(Main.java:138)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by bloxgate** [comment]
Thanks for the report. This is probably an issue on my end, and not a conflict with anything in your pack.

It looks like the Modrinth and CurseForge uploads are different, and the CF one isn't working. It seems there is some issue with the jars uploaded automatically by our action here. I'm guessing that 1.2.1 didn't have its Modrinth build uploaded automatically. Does the version [1.2.2 available on modrinth](https://modrinth.com/mod/tagfoods/version/1.2.2) work for you in your pack?

If so, I'm having some trouble getting that same 1.2.2 to CurseForge, but I can likely have a 1.2.3 up on both with the same change in the next couple days. At least until whatever's going on with the automatic upload is figured out.

**Comment by xFirefalconx** [comment]
Alright thanks for the info! I can give a cautious "1.2.2 seems fine" - I cannot test in-game worlds rn because an other mod also is trolling around, waiting for the fix release on CF there. 
Please keep me updated on 1.2.3, I'll get it from the official port then, Modrinth is a bit weird to implement on CF packs, though I understand it's better support for mod authors. Either way, I'll keep looking out for other issues since I will have to do a couple more bug reports and test runs in the next days.

**Comment by bloxgate** [comment]
Glad to hear it. I'll get 1.2.3 merged after I've had a chance to look at it with fresh eyes tomorrow.

It should close this issue automatically, so you should get notified then.

**Comment by bloxgate** [comment]
[Version 1.2.3](https://legacy.curseforge.com/minecraft/mc-mods/tagfoods/files/4921289) is now available.
